### ISSUE TITLE
File not online?

### ISSUE THREAD

**Issue by DoaaDhaif** [DoaaDhaif/html-validation-fixes#1]
![image](https://user-images.githubusercontent.com/43138805/48652252-8b08a580-e9cc-11e8-889d-b5a188f1a653.png)

**Comment by DoaaDhaif** [comment]
@thomasjbradley
I've been stuck on this file for a while and can't figure out what the last fix I have to do, I've committed and pushed several times, yet I'm still stuck.

**Comment by thomasjbradley** [comment]
Go to the GitHub website and look at the list of files; do they all follow our naming conventions?
